apiVersion: v1
kind: Secret
metadata:
  name: mycluster-secret
  labels:
    argocd.argoproj.io/secret-type: cluster
type: Opaque
stringData:
  name: mycluster.com
  server: https://mycluster.com
  config: |
    {
      "awsAuthConfig": {
        "clusterName": false,
        "roleARN": "<base64 encoded certificate>"
      }
    }
